name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: esgn/pgtuned
      
    - name: Build the Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        repository: esgn/pgtuned
        build_args: POSTGRES_VERSION=14,POSTGIS_VERSION=3
        tags: 14-3, withpostgis-latest
