name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
concurrency: docker-image-ci

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: esgn/pgtuned
      
    - name: Build docker image with latest postgis and postgresql
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        build-args: |
          POSTGRES_VERSION=14
          POSTGIS_VERSION=3
        tags: esgn/pgtuned:14-3, esgn/pgtuned:postgis-latest
        
    - name: Build docker image with latest postgresql but without postgis
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        build-args: |
          POSTGRES_VERSION=14
        tags: esgn/pgtuned:14, esgn/pgtuned:latest

    - name: Build docker image with postgis 2.5 and postgresql 12
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        build-args: |
          POSTGRES_VERSION=12
          POSTGIS_VERSION=2.5
        tags: esgn/pgtuned:12-2.5
