name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-actio@v3.6.2
      with:
        images: esgn/pgtuned
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg POSTGRES_VERSION=14 --build-arg POSTGIS_VERSION=3 --tag my-image-name:14-3 
